### ISSUE TITLE
setup.py does not list iio as a required dependency

### ISSUE THREAD

**Issue by eblot** [analogdevicesinc/pyadi-iio#17]
Should it not?

**Comment by tfcollins** [comment]
The IIO in pip is not libiio so it’s currently just documented to prevent automatic installs of wrong code. A pip install of libiio is something we want to eventually do

**Comment by eblot** [comment]
I'm not sure to understand:

Many Python files from `pyadi-iio` do:

    import iio

which means `pyadi-iio` will not work if `iio` is not installed (whether we want to install it automatically or not), but this dependency is not listed in `setup.py`.

**Comment by tfcollins** [comment]
If you add iio to setup.py it will break the pip installs since iio within pip is a different package but with the same import call.

**Comment by eblot** [comment]
Ok.

**Comment by eblot** [comment]
Sure.
