### ISSUE TITLE
Typo in example?

### ISSUE THREAD

**Issue by eblot** [analogdevicesinc/pyadi-iio#18]
In index.rst, the comment does not seem to match the code:

     # Get both complex channel back
     sdr.rx_enabled_channels = [0]

It seems there is only one channel (`i`?) here.

**Comment by tfcollins** [comment]
I’ll update the comment. Though as documented rx_enabled_channels will return a complex pair for every single index. For non-complex devices these are individual ADCs

**Comment by tfcollins** [comment]
Fixed
