### ISSUE TITLE
Lacking entry for adrv9002 in test/test_map.py

### ISSUE THREAD

**Issue by kimpaller** [analogdevicesinc/pyadi-iio#183]
Lacking entry for adrv9002 in https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/test_map.py

An entry like the ff (shown below) might need to be added:
```
    test_map["adrv9002"] = [
        "zynq-zed-adrv9002",
        "zynq-zed-adrv9002-rx2tx2",
        "zynqmp-zcu102-rev10-adrv9002",
    ]
```

**Comment by tfcollins** [comment]
Added https://github.com/analogdevicesinc/pyadi-iio/blob/master/test/test_map.py
