### ISSUE TITLE
Syntax Error in adi/rx_tx.py

### ISSUE THREAD

**Issue by sunipkmukherjee** [analogdevicesinc/pyadi-iio#41]
Trying to import adi causes this error message:

File "/usr/local/lib/python3.5/dist-packages/adi/rx_tx.py", line 44
    _ctrl: iio.Device = []
           ^
Kernel: 
4.14.0-g622ceadf5354-dirty #8 SMP PREEMPT Thu Aug 8 18:10:14 EDT 2019 armv7l armv7l armv7l GNU/Linux

iio: 0.18 (git tag: c0012d0)

**Comment by tfcollins** [comment]
You need python 3.6+ https://github.com/analogdevicesinc/pyadi-iio/blob/master/setup.py#L32

These are annotations in python.

**Comment by sunipkmukherjee** [comment]
I forgot to mention that I am on Python 3.5.2

**Comment by sunipkmukherjee** [comment]
Yeah I just figured that out! Sorry!
