### ISSUE TITLE
channel not found

### ISSUE THREAD

**Issue by yokihiraHaif98** [analogdevicesinc/pyadi-iio#445]
I'm facing this problem running the example of ad9361 :"Exception: Channel voltage2 not found"

**Comment by tfcollins** [comment]
What hardware are you trying to control?

**Comment by yokihiraHaif98** [comment]
Adalm Pluto sdr "AD9363"

**Comment by tfcollins** [comment]
Pluto by default will only expose 1 complex channel voltage0+voltage1

**Comment by ea-chang** [comment]
Hi, I am having the same issue. I have the latest ADALM-PLUTO and I am trying to receive a signal and I enabled only one transmitter and receiver channel like the example, but I am getting the same exception. These are my settings. 
![image](https://github.com/analogdevicesinc/pyadi-iio/assets/80298714/9b365855-b3ee-44f6-9525-36dd0117bfb8)
