### ISSUE TITLE
Add support for AD2S1210

### ISSUE THREAD

**Issue by pamolloy** [analogdevicesinc/pyadi-iio#455]
## Tasks

- [x] If not already setup, setup hardware for testing

## Dependencies

- adi-ses/sea-misc/issues/15
- adi-ses/sea-misc/issues/2
- analogdevicesinc/hdl/issues/1147 (optional)
- adi-ses/sea-misc/issues/16
- adi-ses/sea-misc/issues/21

**Comment by Skallwar** [comment]
Wrote some code, but I can't test it at the moment since we don't have a setup yet for AS2S1210

**Comment by Skallwar** [comment]
Blocked by adi-ses/sea-misc/issues/15
