### ISSUE TITLE
CN0540 rx_buffer_size does not change after setting sample_rate

### ISSUE THREAD

**Issue by WyattBreitner** [analogdevicesinc/pyadi-iio#466]
Version `0.0.15`

Steps to reproduce:
```
>>> import adi
>>> adc = adi.cn0540.cn0540(uri='ip:localhost')
>>> adc.rx_buffer_size
1024
>>> adc.rx_buffer_size = 100
>>> adc.rx().size
100
>>> adc.sample_rate = 1000
>>> adc.rx().size
100
>>> adc.rx_buffer_size = 10
>>> adc.rx().size
100
>>> adc.rx_buffer_size = 1024
>>> adc.rx().size
100
```

Setup is running on a DE10-Nano with:
Linux-adi `5.10`
libiio `0.23`
python `3.11.2`

**Comment by tfcollins** [comment]
This is expected. Buffer sizing can only take affect when the internal buffers are created or recreated. If you want to change the sizing once to have called rx() you need to destroy the buffers with the rx_destroy_buffer method first.
