### ISSUE TITLE
Installing on Raspberry PI failed.

### ISSUE THREAD

**Issue by LepusMaximus** [analogdevicesinc/pyadi-iio#491]
Hello, I tried to install pyadi-iio on a Raspberry PI.
I build Libiio with python bindings and installed pyadi-iio (Python3.9).

When i try to import adi i get:

`AttributeError: /lib/arm-linu-gnueabihf/libiio.so.1: undefined symbol: iio_get_backends_count`

I do not know how to resolve this. Could anybody help to resolve this?

**Comment by tfcollins** [comment]
See here https://github.com/analogdevicesinc/pyadi-iio/issues/486
