### ISSUE TITLE
add support AD7476a and same.

### ISSUE THREAD

**Issue by karu2003** [analogdevicesinc/pyadi-iio#505]
I build  the driver and the Devicetree. 
Full instructions are [here](https://github.com/karu2003/rpi_ad7476)

in the ADC system it is read.
     \cat /sys/bus/iio/devices/iio\:device0/name\
The test [ad7476.py](https://github.com/karu2003/rpi_ad7476/blob/master/ad7476.py)  does not find the device.

Help me understand where the error is. Maybe the [Devicetree](https://github.com/karu2003/rpi_ad7476/blob/master/rpi-ad7476a-overlay.dts) has an error?
![PXL_20231208_090727102.jpg](https://github.com/analogdevicesinc/pyadi-iio/assets/4937137/a9809131-dc2e-4039-bc88-ab537ea8d1c2)

**Comment by karu2003** [comment]
need to install     
sudo apt install libiio-utils
sudo apt install libiio0
sudo apt install iiod
sudo apt install python3-libiio

**Comment by karu2003** [comment]
I've already checked.  voltage is read.  lib needed to be added to system. :)

**Comment by tfcollins** [comment]
I need the context output so I can see the devices. Remove the -s flag or point it to the local context

**Comment by karu2003** [comment]
Library version: 0.23 (git tag: v0.23)
Compiled with backends: local xml ip usb
IIO context created with local backend.
Backend version: 0.23 (git tag: v0.23)
Backend description string: Linux analog 6.1.65-v8+ #10 SMP PREEMPT Thu Dec  7 08:56:02 UTC 2023 aarch64
IIO context has 2 attributes:
        local,kernel: 6.1.65-v8+
        uri: local:
IIO context has 1 devices:
        iio:device0: ad7476a (buffer capable)
                2 channels found:
                        voltage0:  (input, index: 0, format: be:u12/16>>1)
                        2 channel-specific attributes found:
                                attr  0: raw value: 0
                                attr  1: scale value: 0.805664062
                        timestamp:  (input, index: 1, format: le:S64/64>>0)
                2 device-specific attributes found:
                                attr  0: current_timestamp_clock value: realtime

                                attr  1: waiting_for_supplier value: 0
                3 buffer-specific attributes found:
                                attr  0: data_available value: 0
                                attr  1: direction value: in
                                attr  2: watermark value: 1
ERROR: checking for trigger : Input/output error (5)

**Comment by tfcollins** [comment]
That looks fine. What error do you observe?

**Comment by karu2003** [comment]
what needs to be added there ad7476a_example.py??????
how to add sample rate for iio?

**Comment by karu2003** [comment]
if i add my file to pyadi-iio/adi?
and change everything to

import adi

rate = 1000000      
samples = 5000 
ADC = adi.ad7476a("ip:analog.local")
ADC.sample_rate = rate  
ADC.rx_buffer_size = samples

**Comment by karu2003** [comment]
I thought that sampling could be controlled via iio.
I need to do it self. :(

**Comment by tfcollins** [comment]
Please paste the entire stack trace

**Comment by karu2003** [comment]
analog@analog:~/rpi_ad7476 $ /usr/bin/python3 /home/analog/rpi_ad7476/ad7476.py
ERROR: Open unlocked: -22
Traceback (most recent call last):
  File "/home/analog/rpi_ad7476/ad7476.py", line 63, in <module>
    data = ADC.rx()
  File "/home/analog/.local/lib/python3.9/site-packages/adi/rx_tx.py", line 295, in rx
    data = self.__rx_non_complex()
  File "/home/analog/.local/lib/python3.9/site-packages/adi/rx_tx.py", line 268, in __rx_non_complex
    x = self.__rx_buffered_data()
  File "/home/analog/.local/lib/python3.9/site-packages/adi/rx_tx.py", line 234, in __rx_buffered_data
    self._rx_init_channels()
  File "/home/analog/.local/lib/python3.9/site-packages/adi/rx_tx.py", line 197, in _rx_init_channels
    self.__rxbuf = iio.Buffer(self._rxadc, self.__rx_buffer_size, False)
  File "/usr/local/lib/python3.9/dist-packages/iio.py", line 981, in __init__
    self._buffer = _create_buffer(device._device, samples_count, cyclic)
  File "/usr/local/lib/python3.9/dist-packages/iio.py", line 56, in _check_null
    raise OSError(err, _strerror(err))
OSError: [Errno 22] Invalid argument

**Comment by karu2003** [comment]
When I try to create a buffer for the device, I get the same error.

    dev = ctx.find_device(target_device)
    buf = iio.Buffer(dev, samples)


Traceback (most recent call last):
  File "/home/analog/rpi_ad7476/ad7476.py", line 65, in <module>
    buf = iio.Buffer(dev, samples)
  File "/usr/local/lib/python3.9/dist-packages/iio.py", line 981, in __init__
    self._buffer = _create_buffer(device._device, samples_count, cyclic)
  File "/usr/local/lib/python3.9/dist-packages/iio.py", line 56, in _check_null
    raise OSError(err, _strerror(err))
OSError: [Errno 22] Invalid argument
