### ISSUE TITLE
hrtimer in pyadi?

### ISSUE THREAD

**Issue by karu2003** [analogdevicesinc/pyadi-iio#508]
how to work with hrtimer in pyadi-iio?

**Comment by tfcollins** [comment]
You would need to enable the RTC trigger https://wiki.analog.com/software/linux/docs/iio/iio-trig-sysfs#adding_linux_driver_support and try to map it to your device first

**Comment by karu2003** [comment]
Is there no support in PyAdi-iio.

**Comment by tfcollins** [comment]
The HR timer is no different than any other trigger. As long as you can verify you can use it to drive/trigger your device, you simply set it as a source in your init like so: https://github.com/analogdevicesinc/pyadi-iio/blob/15b7cb999cb5031dfc4f7c8dfa1801a418926fe5/adi/adis16507.py#L34

**Comment by karu2003** [comment]
Thank you. I tried this right away. I made my own timer.
https://github.com/karu2003/rpi_ad7476/blob/master/hrtimer.py

**Comment by tfcollins** [comment]
I think this can be closed now
