### ISSUE TITLE
AttributeError: module 'adi' has no attribute 'adpd410x'

### ISSUE THREAD

**Issue by GoldenxSun** [analogdevicesinc/pyadi-iio#529]
I installed pyadi-iio as shown in the user guide "EVAL-ADPD410x-ARDZ User Guide" (https://wiki.analog.com/resources/eval/user-guides/circuits-from-the-lab/eval-adpd410x) but when I try the first example script (py adpd410x_example.py) I always get this error message "AttributeError: module 'adi' has no attribute 'adpd410x'" even if the library adi is installed in site-packages with all files requiered.  

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/d9ce2f77-f0e8-4160-8544-31bcf8819925)

I also already installed libiio and iio oscilloscope to verify that the hardware is running.
Is there anything I forgot to install or include?

**Comment by tfcollins** [comment]
Can you print the library version?

python -c "import adi ; print(adi.__version__)"

**Comment by GoldenxSun** [comment]
Yes of course. It will throw the same error: "AttributeError: module 'adi' has no attribute '__version__'" as in the following picture

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/54f53673-a1ff-42b4-aa47-f9e3f8735f21)

**Comment by tfcollins** [comment]
Are you sure you have the module installed?  Can you provide the output of pip list and inspect adi:
```
pip list
```

```
python -c "import adi ; print(dir(adi))"
```

**Comment by GoldenxSun** [comment]
Yes pip list shows I have adi.init installed. Seems like I haven't installed the right module.

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/d12aee70-c910-4ce6-9d11-96ab9d35bc63)

and dir(adi) print the following output:

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/7f1610d2-e329-44ea-9433-7b53851569cf)

**Comment by GoldenxSun** [comment]
I installed it via pypi by entering the command "pip install pyadi-iio". It then installed all the libraries in the python site-packages folder. Now when I run the command again it says all required libraries are already installed: "requirement already satisfied"

**Comment by GoldenxSun** [comment]
That's why I am confused. It tells me requirements are already satisfied but on the other hand it can't find the module. Even if it's fully installed in the python site-packages. I have already gone through all the recommended steps and even uninstalled and reinstalled the library.

**Comment by tfcollins** [comment]
Have you removed adi.util? If not then its likely they is higher priority on the import list and will trump pyadi-iio.

**Comment by GoldenxSun** [comment]
Where can I find adi.util?

**Comment by tfcollins** [comment]
Its the package you installed through pip. So running this will remove it:
```
pip uninstall adi.init
```

**Comment by GoldenxSun** [comment]
Okay thank you. But now I get a different error **TypeError: argument of type 'NoneType' is not iterable** after running the following command:

`python -c "import adi ; print(adi.__version__)"`

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/d1f8ce47-f5a8-4dbd-8203-60b277f9a88f)

**Comment by tfcollins** [comment]
You are missing the libiio dependency. See here https://analogdevicesinc.github.io/pyadi-iio/guides/quick.html

**Comment by GoldenxSun** [comment]
Okay, thanks, that worked! Sorry for the misunderstanding. Also, I had to adjust the files cn0540.py, adis16507.py, adxl345.py, adxrs290.py and ltc2983.py because np.float was deprecated and to use the numpy scalar type specifically, I had to use np.float64.

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/a5b9ed06-9aca-47a4-ba68-fafd379a8487)

**Comment by tfcollins** [comment]
Can you provide your installed dependency list and python version?
```
pip list
```
``
python --version
```

**Comment by GoldenxSun** [comment]
Yes of course

![image](https://github.com/analogdevicesinc/pyadi-iio/assets/98425496/2e8dc886-d1ef-4624-8023-da08bd0550c1)

**Comment by tfcollins** [comment]
> Okay, thanks, that worked! Sorry for the misunderstanding. Also, I had to adjust the files cn0540.py, adis16507.py, adxl345.py, adxrs290.py and ltc2983.py because np.float was deprecated and to use the numpy scalar type specifically, I had to use np.float64.

I'm a bit confused here. Do you have a really old clone of the pyadi-iio repo you are using?  This was fixed a long time ago https://github.com/analogdevicesinc/pyadi-iio/commit/ef365218a2b3e536ed734d3645a813cb64bc699d   If you are working in a source tree it should take precedence over installed packages with the same name.

**Comment by GoldenxSun** [comment]
I understand. I was working in the apdp410x branch and probably used an old version of pyadi-iio because of that. This was because I was working with the EVAL-ADPD410x-ARDZ and the example programs are only available under the adpd410x branch. The commit https://github.com/analogdevicesinc/pyadi-iio/commit/ef365218a2b3e536ed734d3645a813cb64bc699d is newer than the apdp410x branch.

**Comment by tfcollins** [comment]
ok. Please don't use branches besides main or packages from pypi/conda. If there is doc pointing to other branches let me know
