### ISSUE TITLE
AD579x not showing up

### ISSUE THREAD

**Issue by rtenacity** [analogdevicesinc/pyadi-iio#550]
In the source files, I can see that there is an ad579x.py file, but I don't see the class in the module files itself. 
<img width="430" alt="image" src="https://github.com/analogdevicesinc/pyadi-iio/assets/50297222/65afbe1c-046f-425a-a011-3ba271fd0c03">
<img width="1557" alt="image" src="https://github.com/analogdevicesinc/pyadi-iio/assets/50297222/29a52d3f-3f41-4a7d-94cb-7daa9098c1d6">

Is this an issue on my end, or is it not in the latest release?

**Comment by tfcollins** [comment]
Not in latest release. Install from main branch
