### ISSUE TITLE
Timeout Error Errno 60

### ISSUE THREAD

**Issue by Caddis03** [analogdevicesinc/pyadi-iio#553]
<img width="685" alt="Screenshot 2024-04-08 at 12 59 54 PM" src="https://github.com/analogdevicesinc/pyadi-iio/assets/67668180/7cd6df6a-474f-4ae8-89a1-5af1172d6902">

Cannot connect to Adam Pluto on Mac using static ip address.

**Comment by tfcollins** [comment]
Have you verified your network settings to the doc https://wiki.analog.com/university/tools/pluto/drivers/osx ?

**Comment by tfcollins** [comment]
Close due to inactivity
