### ISSUE TITLE
Missing Qt plugin when using a virtual enviroment

### ISSUE THREAD

**Issue by JoanOG** [analogdevicesinc/pyadi-iio#582]
Hi,
when running the AD4630 example using a virtual environment in Visual Studio I got the following error:  

qt.qpa.plugin: could not find the qt platform plugin "windows" in "" this application failed to start because no qt platform plugin could be initialized. reinstalling the application may fix this problem.

I managed to solve this issue adding the following variable in the activate.bat but this only works if you run the example from the cmd:

set "QT_PLUGIN_PATH=%VIRTUAL_ENV%\Lib\site-packages\PyQt5\Qt5\plugins" 

when running the code from Visual studio I had to write the following command in the Visual Studio terminal:
set-item env:QT_PLUGIN_PATH "my_project_folder\.venv\Lib\site-packages\PyQt5\Qt5\plugins"

Is it possible to somehow make sure this variables are added?
Regards
Joan

**Comment by tfcollins** [comment]
Which example are you referencing?

**Comment by JoanOG** [comment]
Sorry I forgot to mention which example I was running:

ad4630_example_simple_plot.py

Regards
Joan

**Comment by tfcollins** [comment]
ad4630_example_simple_plot.py does not use QT. Are you sure that is the right one?

**Comment by JoanOG** [comment]
I am 100% sure, I have spent 2 days with this issue until I managed run the AD4630-24

![image](https://github.com/user-attachments/assets/31edbc3c-9956-407d-9f53-4d37c36a4ed2)

**Comment by tfcollins** [comment]
The only thing I can think of is matplotlib using QT as a backend.

To me, having to manipulate the QT dependencies for matplotlib seems like Visual Studio does not have great defaults or you have a custom setup.

matplotlib is one of the most widely used packages and it not working out of the box is uncommon for stock desktop install.

In short this is really too specific to your setup to add to a generic example. If you are having trouble with Visual Studio I would recommend VSCode or PyCharm

**Comment by tfcollins** [comment]
Closed due to inactivity
