### ISSUE TITLE
AD5686 - not possible to have more than one instance

### ISSUE THREAD

**Issue by brunolalb** [analogdevicesinc/pyadi-iio#586]
Because the "channel" variable is a class-variable (declared outside a class function), whenever the class is instantiated, the channel list will be extended by the new device's channel.

```
class ad5686(context_manager, attribute):
    """ AD5686 DAC """

    _complex_data = False
    channel = []  # type: ignore
    _device_name = ""

    def __init__(self, uri="", device_index=0):
        ...
        for ch in self._ctrl.channels:
            name = ch.id
            self.channel.append(self._channel(self._ctrl, name))

        # sort device channels after the index of their index
        self.channel.sort(key=lambda x: int(x.name[7:]))
    ...
```

Also, the scale of the channel is a property of the ad5686._channel class, so when a different ad5686 is instantiated (which has a different scale, this affect all channels of all instances of the ad5686 class.

**Comment by tfcollins** [comment]
This was fixed here https://github.com/analogdevicesinc/pyadi-iio/commit/64990d51a626cdd9cace5a7832ce346159ffe010
