### ISSUE TITLE
This function throws an error

### ISSUE THREAD

**Issue by vagrawal122** [analogdevicesinc/pyadi-iio#588]
https://github.com/analogdevicesinc/pyadi-iio/blob/1dcb979546bd7fc2616dd44a8fb2550399681a6f/adi/adrv9002.py#L708

There seems to be a bug where all of the *_lo functions do not work when I try to get or set the property with the following error:
keyError: "Frequency"

**Comment by tfcollins** [comment]
You likely have an older driver revision. LO properties were changed here https://github.com/analogdevicesinc/pyadi-iio/commit/28917785e9a1e824420353e4062c76c0084bf9d2 
Either revert to v0.0.15 or update to a newer driver revision (SD card release)

**Comment by vagrawal122** [comment]
That was the issue.  Thanks!
