### ISSUE TITLE
Wish: conda package for pyadi-iio (windows)

### ISSUE THREAD

**Issue by petrushy** [analogdevicesinc/pyadi-iio#92]
Hi

It would be very helpful with a conda package for pyadi-iio including the dependency libiio as it seems quite difficult to get this integrated in python as a user on windows.

see conda-forge for more info on conda packaging

Thanks!

**Comment by tfcollins** [comment]
Is this more related to libiio or pyadi-iio? Pip should be in every windows install of python.

Is Pip not part of your normal flow?

-Travis

**Comment by petrushy** [comment]
Hi,

I might have got things wrong, but installing via pip seems only to install the pyadi-ioo library, not the needed dependencies.

Conda is a package manager that can distribute binary python (and other code) packages and libraries in contained environments, typically used in the anaconda python distribution for scientific usage. With this I would imagine it is possible to distribute it with the needed libiio. The windows installer will place the files on the system itself, not in a contained environment. And needs admin privilegies.

**Comment by tfcollins** [comment]
Yes I'm familiar with conda. This issue is more related to libiio though since it doesn't have a pypi or other related installer (yet). This will happen in v0.20 which is slated for June. Once it's there we can look into more packaging options.

**Comment by petrushy** [comment]
Great, yes it is related to libiio and that being separate as a dependency.

Good to hear it is planned! Many thanks!
